# Transcribed from fmv/CREDITS.TGQ (the end-credits video played on exit).
# Roles shown without a label in the video are left blank.
CREDITS = [
    ("Bruce",     "McMillan",  "Executive Producer"),
    ("John",      "Mathieu",   "Associate Producer"),
    ("Mark",      "Bergan",    "Assistant Producer"),
    ("Jon",       "Law",       "Concept & Game Design"),
    ("Dave",      "Colclough", "Lead Programmer"),
    ("Chris",     "Adams",     ""),
    ("David",     "Burton",    ""),
    ("Robin",     "Green",     ""),
    ("Chris",     "Wood",      ""),
    ("Miguel",    "Melo",      "Additional Programming"),
    ("Justin",    "Rae",       "Front End Art"),
    ("Andy",      "Johns",     "Stadium Art"),
    ("Catherine", "Harris",    ""),
    ("Jason",     "Lord",      "Video Art"),
    ("Martin",    "Griffiths", "Video Programming"),
    ("Chris",     "Nicholls",  "Audio Producer"),
    ("Nick",      "Laviers",   "Audio Programming"),
    ("James",     "Hannigan",  "Music"),
    ("Bill",      "Lusty",     "Sound Effects"),
    ("Adelle",    "Kellett",   ""),
    ("David",     "Burton",    "Technical Specialist"),
    ("Darren",    "King",      "Player Database Design"),
    ("Matt",      "Price",     "Test Manager"),
    ("Darren",    "King",      "Lead Tester"),
    ("Lawrence",  "Doyle",     ""),
    ("Julian",    "Glover",    ""),
    ("Darren",    "Tuckey",    ""),
    ("James",     "Lenoel",    "Documentation"),
    ("Margaret",  "Murray",    "Marketing"),
    ("Julie",     "Pain",      "Production"),
    ("Chris",     "Chaplin",   "QA Lead"),
    ("Dominic",   "Murphy",    "QA Tester"),
    ("Kevin",     "Buckner",   "Special Thanks"),
    ("Danny",     "Isaac",     "Special Thanks"),
    ("Neil",      "Cook",      "Special Thanks"),
    ("Jules",     "Burt",      "Special Thanks"),
    ("Matt",      "Eyre",      "Special Thanks"),
    ("Marco",     "Mele",      "Special Thanks"),
]
